package bit.minisys.minicc.parser;

public enum Grammar {
	PROGRAM, FUNCTIONS, FUNCTION, TYPE, FUNC_TYPE,PARAS, PARA, IDENTIFIERS, STMTS, STMT, DECLARE_STMT, RTN_STMT, ASSIGN_STMT, WHILE_STMT, BRANCH_STMT,
	IF_STMT, ELSE_STMT, JU_STMT, EXPR, TERM, EXPR2, TERM2, FACTOR, JU_OPERATOR, IDENTIFIER, OPERATOR, SEPARATOR, KEYWORD, CONSTANT;
}
